Upstream.

diff --git a/cautossh b/cautossh
--- a/cautossh
+++ b/cautossh
@@ -158,6 +158,15 @@ fi
 
 #Override (Program).
 
+#Override, cygwin.
+
+if ! type nmap > /dev/null 2>&1 && type '/cygdrive/c/Program Files (x86)/Nmap/nmap.exe' > /dev/null 2>&1
+then
+	nmap() {
+		'/cygdrive/c/Program Files (x86)/Nmap/nmap.exe' "$@"
+	}
+fi
+
 #Core Auto SSH v1.0
 
 #http://creativecommons.org/publicdomain/zero/1.0/
@@ -1994,6 +2003,13 @@ _testFindPort() {
 	! _wantGetDep ss
 	! _wantGetDep sockstat
 	
+	# WARNING: Cygwin port range detection not yet implemented.
+	if uname -a | grep -i cygwin > /dev/null 2>&1
+	then
+		! type nmap > /dev/null 2>&1 && echo "missing socket detection" && _stop 1
+		return 0
+	fi
+	
 	! type ss > /dev/null 2>&1 && ! type sockstat > /dev/null 2>&1 && echo "missing socket detection" && _stop 1
 	
 	local machineLowerPort=$(cat /proc/sys/net/ipv4/ip_local_port_range 2> /dev/null | cut -f1)
@@ -2029,6 +2045,12 @@ _checkPort_local() {
 	if type sockstat > /dev/null 2>&1
 	then
 		sockstat -46ln | grep '\.'"$1"' ' > /dev/null 2>&1
+		return $?
+	fi
+	
+	if uname -a | grep -i cygwin > /dev/null 2>&1
+	then
+		nmap --host-timeout 0.1 -Pn localhost -p "$1" 2> /dev/null | grep open > /dev/null 2>&1
 		return $?
 	fi
 	
@@ -6121,6 +6143,24 @@ _timetest() {
 	_stop 1
 }
 
+_testarglength() {
+	local testArgLength
+	
+	! testArgLength=$(getconf ARG_MAX) && _messageFAIL && _stop 1
+	
+	
+	# Typical UNIX.
+	if [[ "$testArgLength" -lt 131071 ]]
+	then
+		# Typical Cygwin. Marginal result at best.
+		[[ "$testArgLength" -ge 32000 ]] && uname -a | grep -i 'cygwin' > /dev/null 2>&1 && return 0
+		
+		_messageFAIL && _stop 1
+	fi
+	
+	_messagePASS
+}
+
 #_test_prog() {
 #	true
 #}
@@ -6181,14 +6221,10 @@ _test() {
 	
 	_messagePASS
 	
+	#Environment generated by ubiquitous bash is typically 10000 characters.
 	echo -n -e '\E[1;32;46m Argument length...	\E[0m'
 	
-	local testArgLength
-	
-	! testArgLength=$(getconf ARG_MAX) && _messageFAIL && _stop 1
-	[[ "$testArgLength" -lt 131071 ]] && _messageFAIL && _stop 1
-	
-	_messagePASS
+	_testarglength
 	
 	_messageNormal "Absolute pathfinding..."
 	#_tryExec "_test_getAbsoluteLocation"
