Upstream.

diff --git a/cautossh b/cautossh
--- a/cautossh
+++ b/cautossh
@@ -2258,11 +2258,11 @@ _checkPort_sequence() {
 	fi
 	
 	#Lack of coproc support implies old system, which implies IPv4 only.
-	if ! type coproc >/dev/null 2>&1
-	then
-		_checkPort_ipv4 "$1" "$2"
-		return "$?"
-	fi
+	#if ! type coproc >/dev/null 2>&1
+	#then
+	#	_checkPort_ipv4 "$1" "$2"
+	#	return "$?"
+	#fi
 	
 	( ( _showPort_ipv4 "$1" "$2" ) 2> /dev/null > "$safeTmp"/_showPort_ipv4 & )
 	
@@ -2699,9 +2699,10 @@ _testProxySSH() {
 	! _wantDep vncpasswd && echo 'warn: vncpasswd not found, x11vnc broken!'
 	! _wantDep xset && echo 'warn: xset not found, vnc broken!'
 	
-	! _wantDep pv && echo 'warn: pv not found, benchmark broken'
-	! _wantDep time && echo 'warn: time not found, benchmark broken'
+	#! _wantDep pv && echo 'warn: pv not found, ssh benchmark broken'
+	#! _wantDep time && echo 'warn: time not found, ssh benchmark broken'
 	
+	! _wantDep curl && echo 'warn: curl not found, raw benchmark broken'
 	
 	#! _wantDep xpra && echo 'warn: xpra not found'
 	#! _wantDep xephyr && echo 'warn: xephyr not found'
@@ -3834,6 +3835,56 @@ _ssh_benchmark() {
 }
 
 
+# Stream of pseudorandom bytes to whoever connects. Intended only for benchmarking.
+# "$1" == listen port
+# "$2" == MB (MegaBytes)
+_ssh_benchmark_download_public_source_sequence() {
+	dd if=<(openssl enc -aes-256-ctr -pass pass:"$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" -nosalt < /dev/zero) bs=1M count="$2" iflag=fullblock 2>/dev/null | socat - TCP-LISTEN:"$1" > /dev/null 2>&1 &
+}
+
+_ssh_benchmark_download_public_source() {
+	_nohup "$scriptAbsoluteLocation" _ssh_benchmark_download_public_source_sequence "$@" > /dev/null 2>&1 &
+}
+
+# Establishes raw tunel and transmits random binary data through it as bandwidth test.
+# CAUTION: Generally, SSH connections are to be preferred for simplicity and flexiblity.
+# WARNING: Requires public IP address, LAN IP address, and/or forwarded ports 35500-49075 .
+# WARNING: Intended to produce end-user data. Use multiple specific IPv4 or IPv6 tests at a static address if greater reliability is needed.
+_ssh_benchmark_download_raw() {
+	_start
+	_start_safeTmp_ssh "$@"
+	
+	local currentRemotePublicIPv4
+	currentRemotePublicIPv4=$(_ssh "$@" "$safeTmpSSH"'/cautossh' _find_public_ipv4 | tr -dc 'a-zA-Z0-9.:' )
+	
+	local currentRemotePublicIPv6
+	currentRemotePublicIPv6=$(_ssh "$@" "$safeTmpSSH"'/cautossh' _find_public_ipv4 | tr -dc 'a-zA-Z0-9.:' )
+	
+	local currentRemotePublicPortIPv4
+	currentRemotePublicPortIPv4=$(_ssh "$@" "$safeTmpSSH"'/cautossh' _findPort 35500 49075 | tr -dc 'a-zA-Z0-9.:' )
+	
+	_ssh "$@" "$safeTmpSSH"'/cautossh' _ssh_benchmark_download_public_source "$currentRemotePublicPortIPv4" | tr -dc 'a-zA-Z0-9.:'
+	
+	
+	local currentRemotePublicPortIPv6
+	currentRemotePublicPortIPv6=$(_ssh "$@" "$safeTmpSSH"'/cautossh' _findPort 35500 49075 | tr -dc 'a-zA-Z0-9.:' )
+	
+	_ssh "$@" "$safeTmpSSH"'/cautossh' _ssh_benchmark_download_public_source "$currentRemotePublicPortIPv6" | tr -dc 'a-zA-Z0-9.:'
+	
+	
+	_messagePlain_nominal '_download: public IPv4'
+	_proxy_direct "$currentRemotePublicIPv4" "$currentRemotePublicPortIPv4" | dd of=/dev/null | grep -v records
+	
+	_messagePlain_nominal '_download: public IPv6'
+	_proxy_direct "$currentRemotePublicIPv6" "$currentRemotePublicPortIPv6" | dd of=/dev/null | grep -v records
+	
+	sleep 20
+	
+	_stop_safeTmp_ssh "$@"
+	_stop
+}
+
+
 
 _testAutoSSH() {
 	if ! _wantGetDep /usr/bin/autossh
@@ -4334,6 +4385,8 @@ _testProxyRouter() {
 	
 	_getDep nmap
 	
+	_getDep curl
+	
 	# WARNING: Cygwin does not pass netcat tests.
 	uname -a | grep -i cygwin > /dev/null 2>&1 && return 0
 	
@@ -4444,6 +4497,79 @@ _proxy_reverse() {
 		_proxy "$2" "$currentReversePort"
 	done
 }
+
+# WARNING: Choose reputable services that have been documented alive for at least a few years.
+#https://gist.github.com/yurrriq/7fc7634dd00494072f45
+_find_public_ipv4() {
+	local currentPublicIPaddr
+	
+	currentPublicIPaddr=$(curl --connect-timeout "$netTimeout" -4 -s https://ipv4.icanhazip.com/ | tr -dc 'a-zA-Z0-9.:')
+	[[ "$currentPublicIPaddr" == "" ]] && currentPublicIPaddr=$(curl --connect-timeout "$netTimeout" -4 -s https://ipv4.icanhazip.com/ | tr -dc 'a-zA-Z0-9.:')
+	
+	[[ "$currentPublicIPaddr" == "" ]] && currentPublicIPaddr=$(curl --connect-timeout "$netTimeout" -4 -s https://v4.ident.me/ | tr -dc 'a-zA-Z0-9.:')
+	
+	# CAUTION: Not explicitly IPv4 (though probably nearly so) - https://ipecho.net/developers.html .
+	[[ "$currentPublicIPaddr" == "" ]] && currentPublicIPaddr=$(curl --connect-timeout "$netTimeout" -4 -s https://ipecho.net/plain | tr -dc 'a-zA-Z0-9.:')
+	
+	
+	[[ "$currentPublicIPaddr" == "" ]] && return 1
+	echo -n "$currentPublicIPaddr"
+	return 0
+}
+
+# WARNING: Choose reputable services that have been documented alive for at least a few years.
+#https://gist.github.com/yurrriq/7fc7634dd00494072f45
+_find_public_ipv6() {
+	local currentPublicIPaddr
+	
+	currentPublicIPaddr=$(curl --connect-timeout "$netTimeout" -6 -s https://ipv6.icanhazip.com/ | tr -dc 'a-zA-Z0-9.:')
+	[[ "$currentPublicIPaddr" == "" ]] && currentPublicIPaddr=$(curl --connect-timeout "$netTimeout" -6 -s https://ipv6.icanhazip.com/ | tr -dc 'a-zA-Z0-9.:')
+	
+	[[ "$currentPublicIPaddr" == "" ]] && currentPublicIPaddr=$(curl --connect-timeout "$netTimeout" -6 -s https://v6.ident.me/ | tr -dc 'a-zA-Z0-9.:')
+	
+	
+	[[ "$currentPublicIPaddr" == "" ]] && return 1
+	echo -n "$currentPublicIPaddr"
+	return 0
+}
+
+_find_public_ip() {
+	local currentPublicIPaddr
+	
+	[[ "$currentPublicIPaddr" == "" ]] && currentPublicIPaddr=$(_find_public_ipv6)
+	[[ "$currentPublicIPaddr" == "" ]] && currentPublicIPaddr=$(_find_public_ipv4)
+	
+	
+	[[ "$currentPublicIPaddr" == "" ]] && return 1
+	echo -n "$currentPublicIPaddr"
+	return 0
+}
+
+#https://stackoverflow.com/questions/21336126/linux-bash-script-to-extract-ip-address
+_find_route_ipv4() {
+	#ip route get 8.8.8.8 | awk 'NR==1 {print $NF}'
+	ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}'
+}
+
+#https://stackoverflow.com/questions/21336126/linux-bash-script-to-extract-ip-address
+_find_route_ipv6() {
+	ip route get 2001:4860:4860::8888 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}'
+}
+
+_find_route_ip() {
+	local currentRouteIPaddr
+	
+	[[ "$currentRouteIPaddr" == "" ]] && currentRouteIPaddr=$(_find_route_ipv6)
+	[[ "$currentRouteIPaddr" == "" ]] && currentRouteIPaddr=$(_find_route_ipv4)
+	
+	[[ "$currentRouteIPaddr" == "" ]] && return 1
+	echo -n "$currentRouteIPaddr"
+	return 0
+}
+
+
+
+
 
 
 #Run command and output to terminal with colorful formatting. Controlled variant of "bash -v".
